In [1]:
import webbrowser
import pyautogui as p
import time
import pandas as pd

In [16]:
df1 = pd.read_csv('likes/posts_links.csv')
df1.head()

                                         links
0  https://www.instagram.com/reel/CeafMlFFL67/
1  https://www.instagram.com/reel/CdueFhRM8J8/
2  https://www.instagram.com/reel/CeRhR9ugXnY/
3  https://www.instagram.com/reel/CdglxLCA4rW/
4  https://www.instagram.com/reel/CeiKbVIjjmw/

In [12]:

for link in df1['links']:
    webbrowser.open(link)
    time.sleep(5)  # wait for the page to load
    try:
        unlike_btn = p.locateOnScreen("unlike.png", confidence=0.8)
        print(unlike_btn)
        if unlike_btn:
            p.click(unlike_btn)
            time.sleep(2)
            print(f"Unliked: {link}")
        else:
            print(f"Unlike button not found for: {link}")
    except p.ImageNotFoundException:
        print(f"Unlike button not found for: {link} (exception)")
    p.hotkey('ctrl', 'w')  # close the tab
    df1 = df1[df1['links'] != link]

Unlike button not found for: https://www.instagram.com/reel/CdglxLCA4rW/ (exception)
Unlike button not found for: https://www.instagram.com/reel/CeiKbVIjjmw/ (exception)
Box(left=1222, top=753, width=56, height=36)
Unliked: https://www.instagram.com/p/CejHgyoBMzf/
Box(left=1229, top=754, width=56, height=36)
Unliked: https://www.instagram.com/p/Cef-DhIKdfs/
Box(left=1109, top=751, width=56, height=36)
Unliked: https://www.instagram.com/reel/CeiDIRogP7W/
Box(left=1273, top=751, width=56, height=36)
Unliked: https://www.instagram.com/p/CeiDZAMN0WM/
Box(left=1200, top=754, width=56, height=36)
Unliked: https://www.instagram.com/p/CefTPtlFp9_/
Box(left=1278, top=706, width=56, height=36)
Unliked: https://www.instagram.com/tv/CeczLRDrFw5/
Box(left=1273, top=748, width=56, height=36)
Unliked: https://www.instagram.com/p/Cejnsl0NZGs/
Box(left=1198, top=753, width=56, height=36)
Unliked: https://www.instagram.com/p/CedakuwJjWC/
Box(left=1225, top=755, width=56, height=36)
Unliked: https://www.instagram.com/p/CejF2oItfto/
Box(left=687, top=279, width=56, height=36)
Unliked: https://www.instagram.com/p/CeiGx2yvSZ7/
Box(left=1273, top=753, width=56, height=36)
Unliked: https://www.instagram.com/p/CejDqKOo0wP/
Box(left=1273, top=753, width=56, height=36)
Unliked: https://www.instagram.com/p/Cef_UFJgVib/
Box(left=1109, top=751, width=56, height=36)
Unliked: https://www.instagram.com/reel/Ced0mttDIRY/
Box(left=1221, top=754, width=56, height=36)
Unliked: https://www.instagram.com/p/CejNKDotNw6/
Unlike button not found for: https://www.instagram.com/p/CegADwQlvNt/ (exception)

KeyboardInterrupt:

In [17]:
df1.head()

                                         links
0  https://www.instagram.com/reel/CeafMlFFL67/
1  https://www.instagram.com/reel/CdueFhRM8J8/
2  https://www.instagram.com/reel/CeRhR9ugXnY/
3  https://www.instagram.com/reel/CdglxLCA4rW/
4  https://www.instagram.com/reel/CeiKbVIjjmw/

In [20]:
df1['visited'] = ''

for i,link in enumerate(df1['links']):
    df1.loc[i, 'visited'] = link

In [21]:
df1.head()

,links,visited
0,https://www.instagram.com/reel/CeafMlFFL67/,https://www.instagram.com/reel/CeafMlFFL67/
1,https://www.instagram.com/reel/CdueFhRM8J8/,https://www.instagram.com/reel/CdueFhRM8J8/
2,https://www.instagram.com/reel/CeRhR9ugXnY/,https://www.instagram.com/reel/CeRhR9ugXnY/
3,https://www.instagram.com/reel/CdglxLCA4rW/,https://www.instagram.com/reel/CdglxLCA4rW/
4,https://www.instagram.com/reel/CeiKbVIjjmw/,https://www.instagram.com/reel/CeiKbVIjjmw/

In [ ]:
df1 = pd.read_csv('likes/posts_links.csv')

df1.shape

(113412, 2)