In [1]:
import os

In [4]:
files = os.listdir('.')

In [5]:
files_path = [os.path.join(os.getcwd(),file) for file in files]
files_path

['d:\\Test\\Python\\Insta like\\comments',
 'd:\\Test\\Python\\Insta like\\likes',
 'd:\\Test\\Python\\Insta like\\main.ipynb']

In [6]:
os.listdir('likes/')

['liked_comments.json', 'liked_posts.json']

In [7]:
import pandas as pd

df = pd.read_json("likes\liked_posts.json")
df.head()

                                   likes_media_likes
0  {'title': 'mindsetguides', 'string_list_data':...
1  {'title': 'gohil2116', 'string_list_data': [{'...
2  {'title': 'fattykuds', 'string_list_data': [{'...
3  {'title': 'income.suite', 'string_list_data': ...
4  {'title': 'themermaidscales', 'string_list_dat...

In [21]:
df['likes_media_likes'][0]['string_list_data'][0]['href']

'https://www.instagram.com/reel/CeafMlFFL67/'

In [22]:
df.shape

(113412, 1)

In [31]:
df['likes_media_likes'].apply(lambda x: x['string_list_data'][0]['href'])

0         https://www.instagram.com/reel/CeafMlFFL67/
1         https://www.instagram.com/reel/CdueFhRM8J8/
2         https://www.instagram.com/reel/CeRhR9ugXnY/
3         https://www.instagram.com/reel/CdglxLCA4rW/
4         https://www.instagram.com/reel/CeiKbVIjjmw/
                             ...
113407       https://www.instagram.com/p/C9ezPGMt03I/
113408    https://www.instagram.com/reel/C9fn7bgiHP1/
113409    https://www.instagram.com/reel/C9cYK59J7qd/
113410       https://www.instagram.com/p/C9eXKAmoHLo/
113411       https://www.instagram.com/p/C9e_bohIqqR/
Name: likes_media_likes, Length: 113412, dtype: object

In [32]:
df['links'] = df['likes_media_likes'].apply(lambda x: x['string_list_data'][0]['href'])

In [33]:
df.shape

(113412, 2)

In [34]:
df.head()

,likes_media_likes,links
0,"{'title': 'mindsetguides', 'string_list_data':...",https://www.instagram.com/reel/CeafMlFFL67/
1,"{'title': 'gohil2116', 'string_list_data': [{'...",https://www.instagram.com/reel/CdueFhRM8J8/
2,"{'title': 'fattykuds', 'string_list_data': [{'...",https://www.instagram.com/reel/CeRhR9ugXnY/
3,"{'title': 'income.suite', 'string_list_data': ...",https://www.instagram.com/reel/CdglxLCA4rW/
4,"{'title': 'themermaidscales', 'string_list_dat...",https://www.instagram.com/reel/CeiKbVIjjmw/

In [36]:
df['links'].head()

0    https://www.instagram.com/reel/CeafMlFFL67/
1    https://www.instagram.com/reel/CdueFhRM8J8/
2    https://www.instagram.com/reel/CeRhR9ugXnY/
3    https://www.instagram.com/reel/CdglxLCA4rW/
4    https://www.instagram.com/reel/CeiKbVIjjmw/
Name: links, dtype: object

In [37]:
df1 = df['links']
df1.head()

0    https://www.instagram.com/reel/CeafMlFFL67/
1    https://www.instagram.com/reel/CdueFhRM8J8/
2    https://www.instagram.com/reel/CeRhR9ugXnY/
3    https://www.instagram.com/reel/CdglxLCA4rW/
4    https://www.instagram.com/reel/CeiKbVIjjmw/
Name: links, dtype: object

In [38]:
df1.to_csv('posts_links.csv',index=False)

In [3]:
import webbrowser
import pyautogui as p
import time
import pandas as pd

In [7]:
df1 = pd.read_csv('likes/posts_links.csv')
df1.head()

                                         links
0  https://www.instagram.com/reel/CeafMlFFL67/
1  https://www.instagram.com/reel/CdueFhRM8J8/
2  https://www.instagram.com/reel/CeRhR9ugXnY/
3  https://www.instagram.com/reel/CdglxLCA4rW/
4  https://www.instagram.com/reel/CeiKbVIjjmw/

In [8]:
for links in df1['links'][:4]:
    print(links)

https://www.instagram.com/reel/CeafMlFFL67/
https://www.instagram.com/reel/CdueFhRM8J8/
https://www.instagram.com/reel/CeRhR9ugXnY/
https://www.instagram.com/reel/CdglxLCA4rW/

In [ ]:

for link in df1[:3]:
    webbrowser.open(link)

In [ ]:
# p.position()
unlike_btn = (1130,772)
for link in df1['links']:
    webbrowser.open(link)
    time.sleep(5)  # wait for the page to load
    p.click(unlike_btn)
    time.sleep(2)  # wait before closing the tab
    p.hotkey('ctrl', 'w')  # close the tab
    #also remove those links from the df1
    df1 = df1[df1 != link]

In [9]:
time.sleep(2)
unlike_btn = p.locateOnScreen("unlike.png",confidence=0.5)
if unlike_btn:
    print("Button found at:", unlike_btn)

Button found at: Box(left=331, top=3, width=56, height=36)